---
Name: event-tickets
---
#XD\Events\Model\EventPage:
#  extensions:
#    - 'Broarm\EventTickets\TicketExtension'
#XD\Events\Model\EventPageController:
#  extensions:
#    - 'Broarm\EventTickets\TicketControllerExtension'
#    - 'Broarm\EventTickets\RegisterStep'
#    - 'Broarm\EventTickets\SummaryStep'
#    - 'Broarm\EventTickets\SuccessStep'
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Broarm\EventTickets\Extensions\SiteConfigExtension
SilverStripe\ORM\FieldType\DBCurrency:
  extensions:
    - Broarm\EventTickets\Extensions\CurrencyExtension
SilverStripe\Omnipay\Model\Payment:
  extensions:
    - Broarm\EventTickets\Extensions\TicketPayment
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Broarm\EventTickets\Extensions\GridFieldDetailFormItemRequestExtension
